version: '3'
services:
  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ./docker
    ports:
      - "8083:8083"
    volumes:
      - ./go:/go/src
    command: fresh
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-db
    restart: always
    env_file: .env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/authentication.cnf:/etc/mysql/conf.d/authentication.cnf
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"